export {
  getAssessmentStatusLabel,
  getQuizStatusBadgeClass as getTestStatusBadgeClass,
  getTeacherTestListDisplayStatus,
  canStudentViewTestResults,
  getStudentTestStatus,
  canEditQuizQuestions as canEditTestQuestions,
  aggregateResults as aggregateTestResults,
  MAX_QUIZ_OPTIONS as MAX_TEST_OPTIONS,
  validateQuizOptions as validateTestOptions,
  canActivateQuiz as canActivateTest,
  QUIZ_EXIT_BURST_WINDOW_MS as TEST_EXIT_BURST_WINDOW_MS,
  getQuizExitCount as getTestExitCount,
  emptyQuizFocusSummary as emptyTestFocusSummary,
  summarizeQuizFocusEvents as summarizeTestFocusEvents,
} from '@/lib/quizzes'
