'use client'
import { useState } from 'react'
import { TestQuestionEditor } from '@/components/TestQuestionEditor'
import { StudentTestForm } from '@/components/StudentTestForm'
import { TEST_WORDING_ONLY_MESSAGE } from '@/lib/test-editing-policy'
import { Button, PageDensityProvider } from '@/ui'
import type { TestAssessmentQuestion } from '@/types'

const seed: TestAssessmentQuestion = { id:'14200000-0000-4000-8000-000000000001', test_id:'14200000-0000-4000-8000-000000000002', question_type:'multiple_choice', question_text:'Which statement best explains **inertia**?', options:['Objects resist changes in motion.','Motion always requires a force.','Heavy objects fall faster.','Energy cannot change form.'], correct_option:0, answer_key:null, sample_solution:null, points:2, response_max_chars:5000, response_monospace:false, position:0, created_at:'2026-08-31T12:00:00Z', updated_at:'2026-08-31T12:00:00Z' }
export function TestEditingPolicyFixture() {
 const [question,setQuestion]=useState(seed); const [started,setStarted]=useState(true)
 return <PageDensityProvider density="teacher"><main className="min-h-screen bg-page p-4 text-text-default"><div className="mx-auto max-w-wide space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Development preview</p><h1 className="text-xl font-semibold">Test corrections after Start</h1></div><Button variant="secondary" onClick={()=>setStarted(v=>!v)}>{started?'Show before Start':'Simulate first Start'}</Button></div><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-card border border-border bg-surface"><h2 className="border-b border-border px-4 py-3 font-semibold">Teacher authoring</h2>{started&&<p className="border-b border-border bg-warning-bg px-4 py-2 text-sm text-warning">{TEST_WORDING_ONLY_MESSAGE}</p>}<div className="p-4"><TestQuestionEditor question={question} questionNumber={1} isEditable structureLocked={started} variant="accordion" isExpanded onToggleExpanded={()=>{}} onChange={setQuestion} onDelete={()=>{}} /></div></section><section className="rounded-card border border-border bg-surface"><h2 className="border-b border-border px-4 py-3 font-semibold">Student view</h2><div className="p-4">{started ? <StudentTestForm testId={seed.test_id} questions={[question]} previewMode onSubmitted={()=>{}} /> : <div className="rounded-card border border-border bg-surface-2 p-5"><p className="text-sm text-text-muted">Review the test details, then start when you are ready.</p><Button className="mt-4" onClick={()=>setStarted(true)}>Start the Test</Button></div>}</div></section></div></div></main></PageDensityProvider>
}
