import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { DialogEntryPattern } from '@/app/__ui/DialogEntryPattern'

describe('experimental dialog entry fixture', () => {
  beforeEach(() => {
    const originalComputedStyle = window.getComputedStyle.bind(window)
    vi.spyOn(window, 'getComputedStyle').mockImplementation((element) => {
      const style = originalComputedStyle(element)
      style.setProperty('--motion-duration-standard', '180ms')
      return style
    })
  })

  afterEach(() => {
    cleanup()
    vi.restoreAllMocks()
    vi.useRealTimers()
  })

  it.each(['teacher', 'student'] as const)('exposes both entries and canonical immediate focus for %s', async (role) => {
    const user = userEvent.setup()
    render(<DialogEntryPattern role={role} />)
    expect(screen.getByText(/Experimental/)).toBeInTheDocument()
    const immediate = screen.getByRole('button', { name: 'Open immediate dialog entry' })
    const quiet = screen.getByRole('button', { name: 'Open quiet dialog entry' })
    await user.click(immediate)
    let dialog = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    expect(within(dialog).getByRole('button', { name: 'Close', exact: true })).toHaveFocus()
    expect(within(dialog).getByText('Entry: Immediate')).toBeInTheDocument()
    expect(within(dialog).getByText(`${role === 'teacher' ? 'Teacher' : 'Student'} presentation`)).toBeInTheDocument()
    await user.keyboard('{Escape}')
    expect(immediate).toHaveFocus()
    await user.click(quiet)
    dialog = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    expect(within(dialog).getByRole('button', { name: 'Close', exact: true })).toHaveFocus()
    expect(within(dialog).getByText('Entry: Quiet')).toBeInTheDocument()
    await user.click(within(dialog).getByRole('button', { name: 'Close', exact: true }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(quiet).toHaveFocus()
  })

  it('preserves the live draft node, selection and scroll through local updates, then its backing value on reopen', async () => {
    const user = userEvent.setup()
    render(<DialogEntryPattern role="teacher" />)
    await user.click(screen.getByRole('button', { name: 'Open quiet dialog entry' }))
    const dialog = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    const panelClass = dialog.className
    const input = within(dialog).getByRole('textbox', { name: 'Dialog entry draft' }) as HTMLInputElement
    await user.clear(input)
    await user.type(input, 'Retained classroom note')
    input.setSelectionRange(3, 11)
    const body = screen.getByTestId('dialog-entry-body').parentElement!
    body.scrollTop = 180
    fireEvent.click(within(dialog).getByRole('button', { name: 'Refresh dialog entry metadata' }))
    expect(screen.getByRole('dialog', { name: 'Dialog entry preview' })).toBe(dialog)
    expect(dialog.className).toBe(panelClass)
    expect(within(dialog).getByRole('textbox', { name: 'Dialog entry draft' })).toBe(input)
    expect(input).toHaveValue('Retained classroom note')
    expect(input.selectionStart).toBe(3)
    expect(input.selectionEnd).toBe(11)
    expect(body.scrollTop).toBe(180)
    expect(within(dialog).getByText('Metadata revision: 1')).toBeInTheDocument()
    expect(within(dialog).getByText('Entry: Quiet')).toBeInTheDocument()
    await user.keyboard('{Escape}')
    expect(input).toBeInTheDocument()
    expect(input.closest('[data-modal-state="closing"]')).toHaveAttribute('aria-hidden', 'true')
    await waitFor(() => expect(input).not.toBeInTheDocument())
    await user.click(screen.getByRole('button', { name: 'Open immediate dialog entry' }))
    expect(screen.getByRole('textbox', { name: 'Dialog entry draft' })).toHaveValue('Retained classroom note')
    expect(screen.getByText('Entry: Immediate')).toBeInTheDocument()
  })

  it('lets the canonical top layer handle Escape and restore its opener before closing the parent', async () => {
    const user = userEvent.setup()
    render(<DialogEntryPattern role="student" />)
    const opener = screen.getByRole('button', { name: 'Open quiet dialog entry' })
    await user.click(opener)
    const parent = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    const nestedOpener = within(parent).getByRole('button', { name: 'Open dialog entry confirmation' })
    await user.click(nestedOpener)
    const nested = screen.getByRole('dialog', { name: 'Dialog entry nested confirmation' })
    expect(within(nested).getByRole('button', { name: 'Close', exact: true })).toHaveFocus()
    expect(parent.closest('[aria-hidden="true"]')).not.toBeNull()
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('dialog', { name: 'Dialog entry nested confirmation' })).not.toBeInTheDocument()
    expect(screen.getByRole('dialog', { name: 'Dialog entry preview' })).toBe(parent)
    expect(nestedOpener).toHaveFocus()
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(opener).toHaveFocus()
  })

  it('runs the local destination command immediately and restores background state and focus', async () => {
    const user = userEvent.setup()
    render(<DialogEntryPattern role="student" />)
    const opener = screen.getByRole('button', { name: 'Open quiet dialog entry' })
    const initialOverflow = document.body.style.overflow
    await user.click(opener)
    const dialog = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    expect(document.body.style.overflow).toBe('hidden')
    const command = within(dialog).getByRole('button', { name: 'Select fixture destination' })
    expect(screen.getByTestId('dialog-entry-body').parentElement).not.toContainElement(command)
    await user.click(command)
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByRole('status')).toHaveTextContent('Fixture destination selected: Student history')
    expect(document.body.style.overflow).toBe(initialOverflow)
    expect(opener).toHaveFocus()
    expect(opener.closest('[aria-hidden="true"]')).toBeNull()
  })

  it('dismisses from the actual backdrop immediately while retaining an inert visual exit', async () => {
    const user = userEvent.setup()
    render(<DialogEntryPattern role="teacher" />)
    const opener = screen.getByRole('button', { name: 'Open quiet dialog entry' })
    await user.click(opener)
    const panel = screen.getByRole('dialog')
    await user.click(screen.getByRole('button', { name: 'Close dialog', exact: true }))
    expect(panel).toBeInTheDocument()
    expect(panel.parentElement!.inert).toBe(true)
    await waitFor(() => expect(panel).not.toBeInTheDocument())
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(opener).toHaveFocus()
  })

  it('retains the quiet mode and draft during exit, cancels it on rapid reopen, and keeps immediate mode immediate', () => {
    vi.useFakeTimers()
    render(<DialogEntryPattern role="teacher" />)
    const quiet = screen.getByRole('button', { name: 'Open quiet dialog entry' })
    quiet.focus()
    fireEvent.click(quiet)
    const panel = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    const input = screen.getByRole('textbox', { name: 'Dialog entry draft' })
    fireEvent.change(input, { target: { value: 'Retained draft' } })
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(panel).toBeInTheDocument()
    expect(within(panel).getByText('Entry: Quiet')).toBeInTheDocument()
    expect(input).toHaveValue('Retained draft')
    expect(quiet).toHaveFocus()
    fireEvent.click(quiet)
    expect(screen.getByRole('dialog', { name: 'Dialog entry preview' })).toBe(panel)
    act(() => vi.advanceTimersByTime(180))
    expect(panel).toBeInTheDocument()
    fireEvent.keyDown(document, { key: 'Escape' })
    act(() => vi.advanceTimersByTime(180))
    expect(panel).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Open immediate dialog entry' }))
    const immediate = screen.getByRole('dialog', { name: 'Dialog entry preview' })
    expect(screen.getByRole('textbox', { name: 'Dialog entry draft' })).toHaveValue('Retained draft')
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(immediate).not.toBeInTheDocument()
  })

})
