import { expect, test } from '@playwright/test'

test('roster mirror tracks classic scrollbars and help opens by touch', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ storageState: '.auth/teacher.json', viewport: { width: 390, height: 844 }, hasTouch: true })
  const page = await context.newPage()
  await page.goto('/classrooms')
  await page.getByTestId('classroom-card').first().click()
  await page.waitForURL(/\/classrooms\/[^/?]+/)
  await page.goto(`${page.url().split('?')[0]}?tab=roster`)
  await page.getByRole('button', { name: 'Add students', exact: true }).click()
  const input = page.getByLabel('Enter student information')
  // A stable gutter reproduces the usable-width reduction of classic scrollbars.
  await input.evaluate((element) => { element.style.scrollbarGutter = 'stable' })
  const lines = Array.from({ length: 20 }, (_, index) => `Ada Lovelace student${index}@example.com`)
  await input.fill(lines.join('\n'))
  const mirror = input.locator('..').locator('[aria-hidden="true"]')
  await input.evaluate((element) => { element.scrollTop = 0 })
  await expect.poll(() => mirror.locator(':scope > div').evaluate((element) => element.style.transform)).toBe('translate(0px, 0px)')
  await expect.poll(async () => ({
    input: await input.evaluate((element) => element.clientWidth),
    mirror: await mirror.evaluate((element) => element.clientWidth),
  })).toEqual({ input: await input.evaluate((element) => element.clientWidth), mirror: await input.evaluate((element) => element.clientWidth) })
  const secondLine = mirror.locator(':scope > div > div').nth(1)
  const secondBox = await secondLine.boundingBox()
  expect(secondBox).not.toBeNull()
  await page.mouse.click(secondBox!.x + 2, secondBox!.y + 10)
  const caret = await input.evaluate((element: HTMLTextAreaElement) => element.selectionStart)
  expect(caret).toBeGreaterThanOrEqual(lines[0].length + 1)
  expect(caret).toBeLessThan(lines[0].length + lines[1].length + 2)
  await input.evaluate((element) => { element.scrollTop = element.scrollHeight })
  const lastLine = mirror.locator(':scope > div > div').last()
  await expect.poll(async () => {
    const last = await lastLine.boundingBox()
    const area = await input.boundingBox()
    return Boolean(last && area && last.y >= area.y && last.y + last.height <= area.y + area.height)
  }).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('roster-bottom-scroll.png') })
  const help = page.getByRole('button', { name: 'Roster format help' })
  await help.tap()
  await expect(page.getByRole('tooltip')).toContainText('ID and Email2 are optional')
  await expect(help).toHaveAccessibleDescription(/One student per line/)
  await page.screenshot({ path: testInfo.outputPath('roster-touch-help.png') })
  await help.tap()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await help.tap()
  await input.tap()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await context.close()
})
