import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('ordinary contextual Test creation CI evidence', () => {
  it('runs250 normal and both exact forced cleanup modes serially without changing limits', () => {
    const workflow = readFileSync('.github/workflows/ci.yml', 'utf8')
    const job = workflow.split('  contextual-test-owner-sdk:\n')[1]?.split(/\n  [a-z][a-z-]*:\n/)[0]
    const sibling = workflow.split('  contextual-test-owner-sdk-lifecycle:\n')[1]?.split(/\n  [a-z][a-z-]*:\n/)[0]
    const database = workflow.split('  architecture-database-contracts:\n')[1]?.split(/\n  [a-z][a-z-]*:\n/)[0]
    const databaseLifecycle = workflow.split('  architecture-database-contracts-lifecycle:\n')[1]?.split(/\n  [a-z][a-z-]*:\n/)[0]
    expect(job).toBeDefined()
    expect(database).toContain('run: pnpm run db:types:check')
    expect(database).toContain('name: Rehearse the production-shaped Test identity migration')
    expect(database).not.toContain('name: Verify contextual Daily Log save atomicity and privileges')
    expect(databaseLifecycle).toContain('name: Verify contextual Daily Log save atomicity and privileges')
    expect(databaseLifecycle).toContain('runs-on: ubuntu-latest')
    expect(databaseLifecycle).toContain('run: node scripts/ci-runner-preflight.mjs --lane database-lifecycle')
    expect(databaseLifecycle).toContain('run: supabase start -x analytics,edge-runtime,functions,imgproxy,inbucket,meta,realtime,studio,vector')
    expect(databaseLifecycle).toContain("if: always() && steps.ci-isolation.outcome == 'success' && steps.supabase-start.outcome != 'skipped'")
    expect(databaseLifecycle).toContain('run: supabase stop --no-backup')
    expect(databaseLifecycle!.indexOf('id: ci-isolation')).toBeLessThan(databaseLifecycle!.indexOf('id: supabase-start'))
    expect(databaseLifecycle!.indexOf('name: Verify contextual Daily Log save atomicity and privileges')).toBeGreaterThan(databaseLifecycle!.indexOf('name: Start ephemeral Supabase and replay migrations'))
    expect(databaseLifecycle!.indexOf('name: Verify contextual Daily Log save atomicity and privileges')).toBeLessThan(databaseLifecycle!.indexOf('name: Stop ephemeral database'))
    const name = '      - name: Verify isolated contextual Test owner creation transactions'
    expect(workflow.split(name)).toHaveLength(2)
    expect(job!.split(name)).toHaveLength(2)
    const step = job!.split(name)[1].split('      - name:')[0]
    expect(step).toContain('test_owner_create_head=$(git rev-parse HEAD)')
    expect(step).toContain('pnpm exec tsx scripts/check-contextual-test-owner-create-lifecycle.ts --reviewed-head "$test_owner_create_head" --mode normal')
    expect(step).toContain('for test_owner_create_mode in after-fixture before-capture; do')
    expect(step).toContain('--mode "$test_owner_create_mode" > "$test_owner_create_log" 2>&1 || test_owner_create_status=$?')
    expect(step).toContain('[[ "$test_owner_create_status" -eq 1 ]] || exit 1')
    expect(step).toContain('[[ "$(wc -l < "$test_owner_create_log" | tr -d \' \')" -eq 2 ]] || exit 1')
    expect(step).toContain('chmod 600 "$test_owner_create_log"')
    expect(step).toContain("trap 'rm -f -- \"$test_owner_create_log\"' EXIT")
    expect(step).toContain('grep -Fx "FAIL forced isolated test-owner-create lifecycle: ${test_owner_create_mode}."')
    expect(step).toContain("grep -Fx 'PASS isolated test-owner-create exact teardown and unchanged canonical baseline.'")
    expect(step).not.toMatch(/continue-on-error|--generate-types|wait |tee |\s&\s/)
    expect(job).toContain('id: ci-isolation')
    expect(job).toContain('id: supabase-start')
    expect(job).toContain("if: always() && steps.ci-isolation.outcome == 'success' && steps.supabase-start.outcome != 'skipped'")
    expect(job).toContain('name: Start ephemeral Supabase and replay migrations')
    expect(job).toContain('name: Stop ephemeral database')
    expect(job!.indexOf('id: ci-isolation')).toBeLessThan(job!.indexOf('id: supabase-start'))
    expect(job!.indexOf('name: Start ephemeral Supabase and replay migrations')).toBeLessThan(job!.indexOf(name))
    expect(job!.indexOf(name)).toBeLessThan(job!.indexOf('name: Stop ephemeral database'))
    expect(job).toContain('name: Verify isolated contextual Test owner-draft save transactions')
    expect(job).not.toContain('name: Verify isolated contextual pristine Test draft discard transactions')
    expect(sibling).toContain('name: Verify isolated contextual pristine Test draft discard transactions')
    expect(job!.indexOf('      - name: Verify isolated contextual Test owner-draft save transactions')).toBeLessThan(job!.indexOf(name))
    expect(sibling).toContain('runs-on: ubuntu-latest')
    expect(sibling).toContain('run: node scripts/ci-runner-preflight.mjs --lane test-owner-sdk-lifecycle')
    expect(sibling).toContain('run: supabase start -x analytics,edge-runtime,functions,imgproxy,inbucket,meta,realtime,studio,vector')
    expect(sibling).toContain("if: always() && steps.ci-isolation.outcome == 'success' && steps.supabase-start.outcome != 'skipped'")
    expect(sibling).toContain('run: supabase stop --no-backup')
    expect(sibling!.indexOf('id: ci-isolation')).toBeLessThan(sibling!.indexOf('id: supabase-start'))
    expect(sibling!.indexOf('name: Start ephemeral Supabase and replay migrations')).toBeLessThan(sibling!.indexOf('      - name: Verify isolated contextual pristine Test draft discard transactions'))
    expect(sibling!.indexOf('      - name: Verify isolated contextual pristine Test draft discard transactions')).toBeLessThan(sibling!.indexOf('name: Stop ephemeral database'))
    expect(sibling!.match(/^    timeout-minutes: (\d+)/m)?.[1]).toBe('90')
    expect(job!.match(/^    timeout-minutes: (\d+)/m)?.[1]).toBe('90')
    expect(workflow.match(/name: Architecture Database Contracts[\s\S]*?timeout-minutes: (\d+)/)?.[1]).toBe('90')
  })
})
