import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const workflow = readFileSync('.github/workflows/migrations.yml', 'utf8')

describe('migration workflow authorization boundary', () => {
  it('has only a manual trigger and defaults to preview', () => {
    const triggers = workflow.split('on:\n')[1].split('\npermissions:')[0]
    expect(triggers).toContain('  workflow_dispatch:')
    expect(triggers).not.toMatch(/\n  (push|pull_request|schedule|workflow_run):/)
    expect(triggers).toMatch(/options: \[preview, apply\][\s\S]*?default: preview/)
    expect(triggers).toMatch(/options: \[production\][\s\S]*?default: production/)
  })
  it('isolates main tooling from exact candidate data, binds target environment, and denies apply reruns', () => {
    expect(workflow).toContain("github.ref == 'refs/heads/main'")
    expect(workflow).toContain(".github/workflows/migrations.yml@refs/heads/main")
    expect(workflow).toContain("inputs.mode == 'preview' || github.run_attempt == 1")
    expect(workflow).toMatch(/ref: \$\{\{ github.sha \}\}\n          path: tooling/)
    expect(workflow).toMatch(/ref: \$\{\{ inputs.source_sha \}\}\n          path: candidate/)
    expect(workflow).toContain('environment: migrations-production')
    expect(workflow).toContain("inputs.target == 'production'")
    expect(workflow).toContain('group: manual-migrations-production')
    expect(workflow).not.toContain('staging')
    expect(workflow).toContain('ROLLOUT_BOUND_TARGET: ${{ vars.ROLLOUT_TARGET }}')
    expect(workflow).toContain('SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}')
    expect(workflow.indexOf('Validate dispatch before fetching candidate data')).toBeLessThan(workflow.indexOf('Checkout exact candidate as data'))
    expect(workflow.match(/persist-credentials: false/g)).toHaveLength(2)
  })
  it('pins every setup action to a reviewed immutable commit and verifies the hosted archive before extraction or credentials', () => {
    const uses = [...workflow.matchAll(/uses: ([^\s]+)/g)].map(m => m[1])
    expect(uses).toHaveLength(3)
    expect(uses.every(action => /^[A-Za-z0-9-]+\/[A-Za-z0-9-]+@[a-f0-9]{40}$/.test(action))).toBe(true)
    expect(uses).toContain('actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1')
    expect(uses).toContain('actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38')
    expect(uses.some(action => action.startsWith('supabase/setup-cli'))).toBe(false)
    const hashStep = workflow.split('- name: Install verified Supabase CLI archive')[1]?.split('\n      - name:')[0] ?? ''
    expect(hashStep).toContain('sha256sum --check --status')
    expect(hashStep).toContain("'1eaeee74576b2b296c9731ed729c38ec91f48096be7c10290e324888a310ded7'")
    expect(hashStep).toContain('https://github.com/supabase/cli/releases/download/v2.103.0/supabase_linux_amd64.tar.gz')
    expect(hashStep.indexOf('sha256sum --check --status')).toBeLessThan(hashStep.indexOf('tar -xzf'))
    expect(hashStep.indexOf('sha256sum --check --status')).toBeLessThan(hashStep.indexOf('chmod 700'))
    expect(hashStep.indexOf('sha256sum --check --status')).toBeLessThan(hashStep.indexOf('>> "$GITHUB_PATH"'))
    expect(hashStep).not.toContain('supabase --version')
    expect(hashStep).toContain('x86_64')
    expect(hashStep).not.toMatch(/secrets\.|GH_TOKEN|SUPABASE_ACCESS_TOKEN|SUPABASE_DB_PASSWORD/)
    expect(workflow.indexOf('Install verified Supabase CLI archive')).toBeLessThan(workflow.indexOf('Preview or apply with bound one-time approval'))
    expect(workflow.indexOf('Install verified Supabase CLI archive')).toBeLessThan(workflow.indexOf('${{ secrets.'))
  })
  it('keeps read-only permissions, timeout and per-target serialization, and never interpolates inputs into shell code', () => {
    expect(workflow).toMatch(/permissions:\n  contents: read\n  actions: read/)
    expect(workflow).not.toMatch(/: write\b/)
    expect(workflow).toContain('group: manual-migrations-production')
    expect(workflow).toContain('cancel-in-progress: false')
    expect(workflow).toContain('timeout-minutes: 10')
    expect(workflow).toContain('download/v2.103.0/supabase_linux_amd64.tar.gz')
    const runBlocks = [...workflow.matchAll(/        run: ([\s\S]*?)(?=\n      -|$)/g)].map(m => m[1])
    expect(runBlocks).toHaveLength(3)
    expect(runBlocks.join('\n')).not.toMatch(/\$\{\{|pnpm|db reset|db push|--db-url/)
    expect(runBlocks.join('\n')).toContain('node tooling/scripts/migration-rollout.mjs')
    expect(workflow).not.toContain('upload-artifact')
  })
})
